[phases.setup]
nixpkgs = [
  "libmysqlclient",
  "gcc",
  "python3",
  "pkg-config",
  "mariadb"
]

cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip"
]

[phases.setup.env]
MYSQLCLIENT_CFLAGS = "-I/nix/store/*-mariadb-connector-c-*/include/mariadb"
MYSQLCLIENT_LDFLAGS = "-L/nix/store/*-mariadb-connector-c-*/lib"

[phases.install]
cmds = [
  "/opt/venv/bin/python -m pip install -r requirements.txt"
]

[phases.start]
cmd = "/opt/venv/bin/python app.py"
